services:
  siac-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: siac-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    cpus: 0.10
    mem_limit: 128m
    networks:
      - siac-edge

networks:
  siac-edge:
    name: siac-edge
